version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: memeweaverx3
  bot:
    build: .
    command: dotnet memeweaver.dll
    volumes:
      - ./tmp/memeweaverx3:/publish
    depends_on:
      - db
